Minor touchups to heroku deploying script
plus cleaning out vestigial bits of chef json

diff --git a/bin/heroku-wait-deploy-scale b/bin/heroku-wait-deploy-scale
--- a/bin/heroku-wait-deploy-scale
+++ b/bin/heroku-wait-deploy-scale
@@ -4,17 +4,29 @@ set -o errexit
 set -o pipefail
 
 main() {
-  if [[ $# -ne 3 ]]; then
-    echo "Usage: $(basename "${0}") <repo-slug> <heroku-app> <ps-scale>" >&2
+  local halp='-h|--help|help'
+  if [[ "${*}" =~ $halp ]]; then
+    __usage
+    exit 0
+  fi
+
+  if [[ $# -lt 3 ]]; then
+    __usage
     exit 1
   fi
+
+  [[ "${HEROKU_API_KEY}" ]] || {
+    echo "Missing \$HEROKU_API_KEY" >&2
+    exit 2
+  }
 
   local repo_slug="${1}"
   local heroku_app="${2}"
   local ps_scale="${3}"
+  local version="${4:-master}"
 
   __heroku_wait "${heroku_app}"
-  __heroku_deploy "${repo_slug}" "${heroku_app}"
+  __heroku_deploy "${repo_slug}" "${heroku_app}" "${version}"
   __heroku_scale "${heroku_app}" "${ps_scale}"
 }
 
@@ -23,10 +35,7 @@ __heroku_wait() {
   local timeout="${2:-120}"
   local c=0
 
-  while ! curl \
-    -f -s -n "https://api.heroku.com/apps/${heroku_app}" \
-    -H "Accept: application/vnd.heroku+json; version=3" \
-    -H "Authorization: Bearer ${HEROKU_API_KEY}"; do
+  while ! __heroku_curl -fs "https://api.heroku.com/apps/${heroku_app}"; do
     let c+=10
     if [[ $c -gt ${timeout} ]]; then
       exit 1
@@ -38,34 +47,36 @@ __heroku_wait() {
 __heroku_deploy() {
   local repo_slug="${1}"
   local heroku_app="${2}"
+  local version="${3}"
   local tmp_dir
   tmp_dir="$(mktemp -d)"
   trap 'rm -rf '"${tmp_dir}" EXIT QUIT INT TERM
 
-  printf "\nDeploying %s to %s\n" "${repo_slug}" "${heroku_app}"
-  __make_deploy_request "${repo_slug}" "${heroku_app}" | tee "${tmp_dir}/deploy.json"
+  printf "\nDeploying %s %s to %s\n" \
+    "${repo_slug}" "${version}" "${heroku_app}"
+
+  __make_deploy_request "${repo_slug}" "${heroku_app}" "${version}" \
+    | tee "${tmp_dir}/deploy.json"
 
   local output_stream_url
   output_stream_url="$(jq -r .output_stream_url <"${tmp_dir}/deploy.json")"
 
   printf "\nStreaming deploy output\n"
-  curl -f "${output_stream_url}"
+  __heroku_curl -f "${output_stream_url}"
 }
 
 __make_deploy_request() {
   local repo_slug="${1}"
   local heroku_app="${2}"
+  local version="${3}"
 
-  curl -s -X POST "https://api.heroku.com/apps/${heroku_app}/builds" \
+  __heroku_curl -s -X POST "https://api.heroku.com/apps/${heroku_app}/builds" \
     -d "{
       \"source_blob\": {
         \"url\": \"https://github.com/${repo_slug}/archive/master.tar.gz\",
-        \"version\": \"master\"
+        \"version\": \"${version}\"
       }
-    }" \
-    -H "Authorization: Bearer ${HEROKU_API_KEY}" \
-    -H "Accept: application/vnd.heroku+json; version=3" \
-    -H "Content-Type: application/json"
+    }"
 }
 
 __heroku_scale() {
@@ -76,16 +87,32 @@ __heroku_scale() {
   local formation_scale_qty="${formation_scale%%:*}"
   local formation_scale_size="${formation_scale##*:}"
 
-  curl -s \
-    -X PATCH \
-    "https://api.heroku.com/apps/${heroku_app}/formation/${formation_type}" \
-    -d "{
+  __heroku_curl -s -X PATCH -d "{
       \"quantity\": ${formation_scale_qty},
       \"size\": \"${formation_scale_size}\"
     }" \
+    "https://api.heroku.com/apps/${heroku_app}/formation/${formation_type}"
+}
+
+__heroku_curl() {
+  curl \
+    -n \
     -H "Authorization: Bearer ${HEROKU_API_KEY}" \
     -H "Content-Type: application/json" \
-    -H "Accept: application/vnd.heroku+json; version=3"
+    -H "Accept: application/vnd.heroku+json; version=3" \
+    "${@}"
+}
+
+__usage() {
+  cat >&2 <<EOF
+Usage: $(basename "${0}") <slug> <app> <scale> [version]
+
+Deploy Heroku app named <app> from GitHub repo with <slug> at dyno <scale>,
+optionally at a specific [version], e.g.:
+
+    $(basename "${0}") travis-ci/flurb travis-flurb-prod web=1:Hobby fafafaf
+
+EOF
 }
 
 main "${@}"
